public enum EspecializacaoMedico {
    PEDIATRIA, PSICOLOGIA, FISIOTERAPIA, CARDIOLOGIA, UROLOGIA, GINECOLOGIA, DEMATORLOGIA, ANESTESIOLOGIA, ODONTOLOGIA, ENDOCRINOLOGIA, RADIOLOGIA, OTORRINOLARINGOLOGIA ,ONCOLOGIA, OFTALMOLOGIA, ORTOPEDIA, NEUROLOGIA, HEMATOLOGIA, GASTROENTEROLOGIA, ALERGOLOGIA, PNEUMOLOGIA, NEFROLOGIA, IMUNOLOGIA, INFECTOLOGIA,
}
