public enum TipoExame {
    FISIOTERAPIA, CARDIOLOGIA, UROLOGIA, GINECOLOGIA, ODONTOLOGIA, ENDOCRINOLOGIA, RADIOLOGIA, OTORRINOLARINGOLOGIA ,ONCOLOGIA, OFTALMOLOGIA, ORTOPEDIA, NEUROLOGIA, HEMATOLOGIA, GASTROENTEROLOGIA, ALERGOLOGIA, PNEUMOLOGIA, NEFROLOGIA, IMUNOLOGIA, INFECTOLOGIA,

}
